= AUC

*auc* is a high-performance, lightweight auto-clicker implemented in C11. This project uses `libuiohook` library to interact with native input events directly at the operating system level.

*auc* provides a robust, low-latency framework for automating mouse interactions across the entire desktop environment. You are given choice to customise the click frequency with millisecond-precision intervals.

Additionally, the application supports burst-clicking and allows you to define the exact number of mouse clicks executed per interval.

== BUILD INSTRUCTIONS

*PREREQUISITES:*

* Standard C11-compliant compiler
* CMake
* libuiohook

Obtain a local copy of this repository
[source,shell]
----
%  git clone https://github.com/vs-123/auc.git
----

Create a `build/` directory inside the project root and use  to build
[source,shell]
----
%  cd auc
%  mkdir build
%  cmake ..
%  cmake --build .
----

You may execute the generated binary `auc`
[source,shell]
----
%  ./auc --help
----

== LICENSE

This project is licensed under the GNU Affero General Public License version 3.0 or later.

*NO WARRANTY PROVIDED*

For full terms, visit https://www.gnu.org/licenses/agpl-3.0.en.html.

